name: cuchitoapp
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^8.2.1
  cloud_firestore: ^0.13.7
  firebase_core: ^0.4.5
  firebase_analytics: ^5.0.16
  firebase_auth: any
  firebase_database: ^3.1.6
  google_sign_in: ^4.5.1
  screen: ^0.0.5
  camera: ^0.5.8+5
  path_provider: ^1.6.14
  image_picker: ^0.6.7+6
  cached_network_image:
 
 
  
  
  


  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"
  
  

flutter_icons:
  ios: true
  android: true
  image_path: "icono/android.jpeg"


flutter:

  uses-material-design: true


  assets:
    - assets/images/foto2.png
    - assets/images/foto1.png
    - assets/images/foto3.png

  fonts:
     - family: Billabong
       fonts:
         - asset: assets/fonts/Billabong.ttf
  